/*
** EPITECH PROJECT, 2023
** RPG
** File description:
** ressources
*/

#ifndef RESSOURCES_TEXTURES_H_
    #define RESSOURCES_TEXTURES_H_

typedef enum e_texture {
    TX_APP_ICON,
    TX_DIALOG_MENU_BGR,
    TX_CHARACTERE_1,
    TX_BACKGROUND_MENU,
    TX_INVENTORY_COMPO,
    TX_UI_MENU_ALL,
    TX_UI_ELEMENTS,
    TX_CHALICE,
    TX_NATURE,
    TX_SHIP,
    TX_CAMPFIRE,
    TX_NPC_ATTENTION,
    TX_SHRINE_ACTIVATING,
    TX_SHRINE_AVAILABLE,
    TX_ALTAR_1,
    TX_ALTAR_AURA,
    TX_OBELISK_ACTIVATING,
    TX_OBELISK_DEACTIVATING,
    TX_PARTICALES,
    TX_RITUALS,
    TX_FOUNTAIN,
    TX_LEN
} texture_t;

#endif /* !RESSOURCES_TEXTURES_H_ */
