name: Check-Execution

on:
  workflow_call:
    inputs:
      executables:
        description: 'List of executable files to check'
        required: true
        type: string

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: "epitechcontent/epitest-docker"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Compile program
        run: |
          make
        timeout-minutes: 2
      - name: Clean
        run: |
          make clean
      - name: Available executables
        run: |
          for executable in ${{ inputs.executables }}; do
            if [ ! -x "$executable" ]; then
              echo "::error title="Error : not found or not executable"::$executable"
              exit 1
            fi
          done

  run_tests:
    needs: [ check_program_compilation ]
    runs-on: ubuntu-latest
    container:
      image: "epitechcontent/epitest-docker"
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          make tests_run

  run_size_check:
    needs: [ check_program_compilation ]
    runs-on: ubuntu-latest
    steps:
      - name: Check size repo
        uses: actions/checkout@v3
      - name: Run check size
        run : |
          repo_size=$(git ls-tree -r --name-only main | xargs du -c --exclude=".git" | tail -n 1 | awk '{print $1}')
          repo_size_commande=$(git ls-tree -r --name-only main | xargs du -h -c --exclude=".git" | tail -n 1 | awk '{print $1}')
          if [ $repo_size -gt 30000 ]; then
            echo "::error title="Error : Repo size is greater than 30 MB."::$repo_size_commande"
            exit 1
          else
            echo "### Repo size is good! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
            echo "## $repo_size_commande" >> $GITHUB_STEP_SUMMARY
          fi

